In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/akshay7029/Project_DBDA/main/health_fitness_dataset_P.csv')

In [ ]:
df.head()

,id,Sex,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories,hydration_level,Season,Intensity,hours_sleep,Mood
0,0,male,36,189.0,82,26,101.0,41.0,150,6.72,Winter,Medium,8.6,Calm
1,1,female,64,163.0,60,8,85.0,39.7,34,5.86,Autumn,High,6.5,Sad
2,2,female,51,161.0,64,7,84.0,39.8,29,0.76,Winter,Medium,8.0,Calm
3,3,male,20,192.0,90,25,105.0,40.7,140,7.81,Spring,Low,6.9,Angry
4,4,female,38,166.0,61,25,102.0,40.6,146,5.92,Autumn,High,7.1,Happy

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               750000 non-null  int64
 1   Sex              750000 non-null  object
 2   Age              750000 non-null  int64
 3   Height           750000 non-null  float64
 4   Weight           750000 non-null  int64
 5   Duration         750000 non-null  int64
 6   Heart_Rate       750000 non-null  float64
 7   Body_Temp        750000 non-null  float64
 8   Calories         750000 non-null  int64
 9   hydration_level  750000 non-null  float64
 10  Season           750000 non-null  object
 11  Intensity        750000 non-null  object
 12  hours_sleep      740000 non-null  float64
 13  Mood             750000 non-null  object
dtypes: float64(5), int64(5), object(4)
memory usage: 80.1+ MB

In [ ]:
df.isnull().sum()

id                     0
Sex                    0
Age                    0
Height                 0
Weight                 0
Duration               0
Heart_Rate             0
Body_Temp              0
Calories               0
hydration_level        0
Season                 0
Intensity              0
hours_sleep        10000
Mood                   0
dtype: int64

In [ ]:
df['hours_sleep'] = df['hours_sleep'].interpolate()

In [ ]:
df.isnull().sum()

id                 0
Sex                0
Age                0
Height             0
Weight             0
Duration           0
Heart_Rate         0
Body_Temp          0
Calories           0
hydration_level    0
Season             0
Intensity          0
hours_sleep        0
Mood               0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               750000 non-null  int64
 1   Sex              750000 non-null  object
 2   Age              750000 non-null  int64
 3   Height           750000 non-null  float64
 4   Weight           750000 non-null  int64
 5   Duration         750000 non-null  int64
 6   Heart_Rate       750000 non-null  float64
 7   Body_Temp        750000 non-null  float64
 8   Calories         750000 non-null  int64
 9   hydration_level  750000 non-null  float64
 10  Season           750000 non-null  object
 11  Intensity        750000 non-null  object
 12  hours_sleep      750000 non-null  float64
 13  Mood             750000 non-null  object
dtypes: float64(5), int64(5), object(4)
memory usage: 80.1+ MB

In [ ]:
sex_mapping = {'male': 0, 'female': 1}
df['Sex'] = df['Sex'].map(sex_mapping)

In [ ]:
mood_mapping = {'Calm': 3, 'Sad': 2, 'Happy': 4, 'Angry': 0, 'Scared': 1}
df['Mood'] = df['Mood'].map(mood_mapping)

In [ ]:
df = pd.get_dummies(df, columns=['Season', 'Intensity'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                750000 non-null  int64
 1   Sex               750000 non-null  int64
 2   Age               750000 non-null  int64
 3   Height            750000 non-null  float64
 4   Weight            750000 non-null  int64
 5   Duration          750000 non-null  int64
 6   Heart_Rate        750000 non-null  float64
 7   Body_Temp         750000 non-null  float64
 8   Calories          750000 non-null  int64
 9   hydration_level   750000 non-null  float64
 10  hours_sleep       750000 non-null  float64
 11  Mood              750000 non-null  int64
 12  Season_Autumn     750000 non-null  bool
 13  Season_Spring     750000 non-null  bool
 14  Season_Summer     750000 non-null  bool
 15  Season_Winter     750000 non-null  bool
 16  Intensity_High    750000 non-null  bool
 17  Intensity_Low     750000 non-null  bool
 18  Intensity_Medium  750000 non-null  bool
dtypes: bool(7), float64(5), int64(7)
memory usage: 73.7 MB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('Calories', axis=1)
y = df['Calories']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (525000, 18)
Shape of X_test: (225000, 18)
Shape of y_train: (525000,)
Shape of y_test: (225000,)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 123.27761984990124
R-squared: 0.9682672451737582

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# Initialize the Random Forest Regressor model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Regressor - Mean Squared Error:", mse_rf)
print("Random Forest Regressor - R-squared:", r2_rf)

Random Forest Regressor - Mean Squared Error: 14.637958935555554
Random Forest Regressor - R-squared: 0.9962320592932915

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

# Initialize the Gradient Boosting Regressor model
gbr_model = GradientBoostingRegressor(n_estimators=100, random_state=42)

# Train the model
gbr_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_gbr = gbr_model.predict(X_test)

# Evaluate the model
mse_gbr = mean_squared_error(y_test, y_pred_gbr)
r2_gbr = r2_score(y_test, y_pred_gbr)

print("Gradient Boosting Regressor - Mean Squared Error:", mse_gbr)
print("Gradient Boosting Regressor - R-squared:", r2_gbr)

Gradient Boosting Regressor - Mean Squared Error: 22.451169824927
Gradient Boosting Regressor - R-squared: 0.9942208693801505